export default {
  body: null,
  headers: {
    Accept: '*/*',
    Authorization: 'Bearer tometoken',
    'CloudFront-Forwarded-Proto': 'https',
    'CloudFront-Is-Desktop-Viewer': 'true',
    'CloudFront-Is-Mobile-Viewer': 'false',
    'CloudFront-Is-SmartTV-Viewer': 'false',
    'CloudFront-Is-Tablet-Viewer': 'false',
    'CloudFront-Viewer-Country': 'GB',
    Origin: 'https://www.somesite.com',
    Host: 'apigwid.execute-api.us-east-1.amazonaws.com',
    'User-Agent': 'curl/7.68.0',
    Via: '2.0 e4094f3d427f11ea8b257166e26f7db2.cloudfront.net (CloudFront)',
    'X-Amz-Cf-Id': 'TbWjXEC2dFD4E7zpU33-V9jp5iC0dCL_aywPx-CbXlC6GF_1VEiI7A==',
    'X-Amzn-Trace-Id': 'Root=1-62c338f0-1a54eb97736d2a7a2926b2fc',
    'X-Forwarded-For': '217.155.43.244, 130.176.222.187',
    'X-Forwarded-Port': '443',
    'X-Forwarded-Proto': 'https',
  },
  httpMethod: 'GET',
  isBase64Encoded: false,
  multiValueHeaders: {
    Accept: ['*/*'],
    Authorization: ['Bearer tometoken'],
    'CloudFront-Forwarded-Proto': ['https'],
    'CloudFront-Is-Desktop-Viewer': ['true'],
    'CloudFront-Is-Mobile-Viewer': ['false'],
    'CloudFront-Is-SmartTV-Viewer': ['false'],
    'CloudFront-Is-Tablet-Viewer': ['false'],
    'CloudFront-Viewer-Country': ['GB'],
    Host: ['apigwid.execute-api.us-east-1.amazonaws.com'],
    'User-Agent': ['curl/7.68.0'],
    Via: ['2.0 e4094f3d427f11ea8b257166e26f7db2.cloudfront.net (CloudFront)'],
    'X-Amz-Cf-Id': ['TbWjXEC2dFD4E7zpU33-V9jp5iC0dCL_aywPx-CbXlC6GF_1VEiI7A=='],
    'X-Amzn-Trace-Id': ['Root=1-62c338f0-1a54eb97736d2a7a2926b2fc'],
    'X-Forwarded-For': ['217.155.43.244, 130.176.222.187'],
    'X-Forwarded-Port': ['443'],
    'X-Forwarded-Proto': ['https'],
  },
  multiValueQueryStringParameters: {
    sourceUrl: ['https://cdn.test.com/drums.wav'],
  },
  path: '/',
  pathParameters: null,
  queryStringParameters: {
    sourceUrl: 'https://cdn.test.com/drums.wav',
  },
  requestContext: {
    accountId: '715905027390',
    apiId: 'apigwid',
    authorizer: {
      allowedAudioOrigins: 'https://d2m8h53em6mi65.cloudfront.net',
      aud: 'api.sound.ws',
      exp: '1688130426',
      iat: '1656594426',
      integrationLatency: 647,
      principalId: 'Unknown',
    },
    domainName: 'apigwid.execute-api.us-east-1.amazonaws.com',
    domainPrefix: 'apigwid',
    extendedRequestId: 'UwXVkEr4oAMFy6A=',
    httpMethod: 'GET',
    identity: {
      accessKey: null,
      accountId: null,
      caller: null,
      cognitoAuthenticationProvider: null,
      cognitoAuthenticationType: null,
      cognitoIdentityId: null,
      cognitoIdentityPoolId: null,
      principalOrgId: null,
      sourceIp: '217.155.43.244',
      user: null,
      userAgent: 'curl/7.68.0',
      userArn: null,
    },
    path: '/dev/',
    protocol: 'HTTP/1.1',
    requestId: 'cfe0ba39-18aa-47d8-bae5-1ed0931ee6b2',
    requestTime: '04/Jul/2022:19:01:04 +0000',
    requestTimeEpoch: 1656961264276,
    resourceId: 'dkkakymoil',
    resourcePath: '/',
    stage: 'dev',
  },
  resource: '/',
  stageVariables: null,
};
